name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-20.04']
        php-versions: ['8.0', '8.1']
        phpunit-versions: ['9.5.4']
        include:
        - operating-system: 'ubuntu-16.04'
          php-versions: '5.3'
          phpunit-versions: '4.8.36'
        - operating-system: 'ubuntu-18.04'
          php-versions: '7.1'
          phpunit-versions: '4.8.36'

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug
        tools: phpunit:${{ matrix.phpunit-versions }}

    - uses: actions/checkout@v2

    - run: composer require "phpunit/phpunit:${{ matrix.phpunit-versions }}" --no-update

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ matrix.php-versions }}-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: composer install --prefer-source --no-interaction --dev

    - name: Run tests
      run: ./vendor/bin/phpunit
