name: PHP Composer

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.operating-system }}
    strategy:
      matrix:
        operating-system: ['ubuntu-20.04']
        php-versions: ['8.0']
        phpunit-versions: ['9.5.4']
        coverage: [false]
        include:
        - php-versions: '5.3'
          operating-system: 'ubuntu-16.04'
          phpunit-versions: '4.8.36'
        - php-versions: '5.4'
          operating-system: 'ubuntu-16.04'
          phpunit-versions: '4.8.36'
        - php-versions: '5.5'
          operating-system: 'ubuntu-16.04'
          phpunit-versions: '4.8.36'
        - php-versions: '5.6'
          operating-system: 'ubuntu-16.04'
          phpunit-versions: '4.8.36'
        - php-versions: '7.0'
          operating-system: 'ubuntu-16.04'
          phpunit-versions: '4.8.36'
        - php-versions: '7.1'
          operating-system: 'ubuntu-18.04'
          phpunit-versions: '4.8.36'
        - php-versions: '7.2'
          operating-system: 'ubuntu-18.04'
          phpunit-versions: '4.8.36'
        - php-versions: '7.3'
          operating-system: 'ubuntu-18.04'
          phpunit-versions: '7.5.20'
        - php-versions: '7.4'
          operating-system: 'ubuntu-20.04'
          phpunit-versions: '7.5.20'
          coverage: true

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php-versions }}
        coverage: xdebug
        tools: phpunit:${{ matrix.phpunit-versions }}

    - uses: actions/checkout@v2

    - name: Run tests
      run: ./vendor/bin/phpunit
      if: ${{ !matrix.coverage }}

    - name: Run tests with coverage
      run: |
       phpunit --coverage-clover clover.xml
      if: ${{ matrix.coverage }}

    - name: Upload coverage results to Coveralls
      env:
        COVERALLS_REPO_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        composer global require php-coveralls/php-coveralls
        php-coveralls --coverage_clover=clover.xml -v
      if: ${{ matrix.coverage }}
